
name: Build without test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]
  workflow_dispatch:
jobs:
  build-without-test:
    uses: Roadhog360/Hog-Actions-Workflows/.github/workflows/build-and-test.yml@master
    #Change the above to "build-without-test" and the name to "Build without test" if you don't want this build to run a test server
    secrets: inherit
